### ISSUE TITLE
Error when trying to publish to Azure

### ISSUE THREAD

**Issue by bryanbenetti** [TwilioDevEd/sdk-starter-csharp-deprecated#11]
Hi,

Severity	Code	Description	Project	File	Line	Suppression State
Error		The command "bower install" exited with code 9009.	sdkstarter	C:\Users\bryan\OneDrive\Documents\Visual Studio 2017\Projects\sdk-starter-csharp-master\src\sdkstarter\sdkstarter.csproj	46

**Comment by smendes** [comment]
Thank you for the report. With this [@joliveros PR](https://github.com/TwilioDevEd/sdk-starter-csharp/pull/12) it should be fixed now.
